'use client';

import { FormEvent, useState } from 'react';
import styles from './planner-shell.module.css';

export type TodoListRow = { id: string; name: string; color: string | null; position: number };
export type TodoTaskRow = { id: string; list_id: string | null; title: string; description: string | null; status: 'pending' | 'done'; priority: 'low' | 'normal' | 'high'; agenda_date: string | null; time_slot_id: string | null; reminder_time: string | null; position: number };
type Slot = { id: string; name: string; start_time: string | null; end_time: string | null; color: string | null };
export type TodoDraft = Omit<TodoTaskRow, 'id' | 'position' | 'status'>;

export function TodoModule({ lists, tasks, slots, onAddList, onSave, onToggle, onDelete }: { lists: TodoListRow[]; tasks: TodoTaskRow[]; slots: Slot[]; onAddList: (name: string) => Promise<void>; onSave: (draft: TodoDraft, task?: TodoTaskRow) => Promise<boolean>; onToggle: (task: TodoTaskRow) => Promise<void>; onDelete: (task: TodoTaskRow) => Promise<void> }) {
  const [listId, setListId] = useState<string | 'all' | 'today' | 'undated' | 'done'>('all');
  const [editor, setEditor] = useState<TodoTaskRow | 'new' | null>(null);
  const [quickTitle, setQuickTitle] = useState('');
  const today = new Date().toLocaleDateString('en-CA');
  const visible = tasks.filter((task) => listId === 'all' ? task.status === 'pending' : listId === 'today' ? task.agenda_date === today && task.status === 'pending' : listId === 'undated' ? !task.agenda_date && task.status === 'pending' : listId === 'done' ? task.status === 'done' : task.list_id === listId && task.status === 'pending').sort((a, b) => a.position - b.position);
  async function addList() { const name = window.prompt('Liste adı'); if (name?.trim()) await onAddList(name.trim()); }
  async function quickAdd(event: FormEvent) { event.preventDefault(); if (!quickTitle.trim()) return; const inbox = lists.find((list) => list.name.toLocaleLowerCase('tr') === 'gelen kutusu') ?? lists[0]; const saved = await onSave({ title: quickTitle.trim(), description: null, list_id: inbox?.id ?? null, priority: 'normal', agenda_date: null, time_slot_id: null, reminder_time: null }); if (saved) setQuickTitle(''); }
  return <section className={styles.todoModule}><header><div><span>Tek seferlik işler</span><h2>Todo</h2></div><button onClick={() => setEditor('new')}>＋ Görev</button></header><form className={styles.todoQuickAdd} onSubmit={quickAdd}><input value={quickTitle} onChange={(event) => setQuickTitle(event.target.value)} placeholder="Görev yaz ve Enter'a bas…" /><button disabled={!quickTitle.trim()}>＋</button></form><div className={styles.todoSmartFilters}><button className={listId === 'all' ? styles.todoListActive : ''} onClick={() => setListId('all')}>Açık</button><button className={listId === 'today' ? styles.todoListActive : ''} onClick={() => setListId('today')}>Bugün</button><button className={listId === 'undated' ? styles.todoListActive : ''} onClick={() => setListId('undated')}>Tarihsiz</button><button className={listId === 'done' ? styles.todoListActive : ''} onClick={() => setListId('done')}>Tamamlanan</button></div><div className={styles.todoLists}>{lists.map((list) => <button key={list.id} className={listId === list.id ? styles.todoListActive : ''} onClick={() => setListId(list.id)}>{list.name}</button>)}<button onClick={() => void addList()}>＋ Liste</button></div><div className={styles.todoTasks}>{visible.map((task) => <article key={task.id} className={task.status === 'done' ? styles.todoDone : ''}><button className={styles.todoCheck} onClick={() => void onToggle(task)}>{task.status === 'done' ? '✓' : ''}</button><button className={styles.todoIdentity} onClick={() => setEditor(task)}><strong>{task.title}</strong><small>{lists.find((list) => list.id === task.list_id)?.name ?? 'Gelen Kutusu'}{task.agenda_date ? ` · ${new Intl.DateTimeFormat('tr-TR', { day: 'numeric', month: 'short' }).format(new Date(`${task.agenda_date}T00:00:00`))}` : ''}{task.reminder_time ? ` · 🔔 ${task.reminder_time.slice(0, 5)}` : ''}</small></button>{task.priority === 'high' && <span className={styles.todoPriority}>!</span>}</article>)}{!visible.length && <div className={styles.empty}>Bu görünümde görev yok.</div>}</div>{editor && <TodoEditor task={editor === 'new' ? undefined : editor} lists={lists} slots={slots} onClose={() => setEditor(null)} onSave={async (draft) => { const saved = await onSave(draft, editor === 'new' ? undefined : editor); if (saved) setEditor(null); return saved; }} onDelete={editor !== 'new' ? async () => { await onDelete(editor); setEditor(null); } : undefined} />}</section>;
}

function TodoEditor({ task, lists, slots, onClose, onSave, onDelete }: { task?: TodoTaskRow; lists: TodoListRow[]; slots: Slot[]; onClose: () => void; onSave: (draft: TodoDraft) => Promise<boolean>; onDelete?: () => Promise<void> }) {
  const [title, setTitle] = useState(task?.title ?? ''); const [description, setDescription] = useState(task?.description ?? ''); const [listId, setListId] = useState(task?.list_id ?? lists[0]?.id ?? ''); const [priority, setPriority] = useState<TodoTaskRow['priority']>(task?.priority ?? 'normal'); const [inAgenda, setInAgenda] = useState(!!task?.agenda_date); const [date, setDate] = useState(task?.agenda_date ?? new Date().toLocaleDateString('en-CA')); const [slotId, setSlotId] = useState(task?.time_slot_id ?? slots[0]?.id ?? ''); const [reminder, setReminder] = useState(task?.reminder_time?.slice(0, 5) ?? ''); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); await onSave({ title: title.trim(), description: description.trim() || null, list_id: listId || null, priority, agenda_date: inAgenda ? date : null, time_slot_id: inAgenda ? slotId : null, reminder_time: inAgenda && reminder ? reminder : null }); setBusy(false); }
  return <div className={styles.overlay} onMouseDown={onClose}><form className={`${styles.metricDialog} ${styles.todoEditor}`} onSubmit={submit} onMouseDown={(event) => event.stopPropagation()}><div className={styles.dialogTop}><span>{task ? 'Görevi düzenle' : 'Yeni görev'}</span><button type="button" onClick={onClose}>×</button></div><h2>{task?.title || 'Yapılacak iş'}</h2><label>Başlık<div><input required value={title} onChange={(event) => setTitle(event.target.value)} autoFocus /></div></label><label>Açıklama<textarea rows={3} value={description} onChange={(event) => setDescription(event.target.value)} /></label><div className={styles.todoEditorGrid}><label>Liste<select value={listId} onChange={(event) => setListId(event.target.value)}>{lists.map((list) => <option key={list.id} value={list.id}>{list.name}</option>)}</select></label><label>Öncelik<select value={priority} onChange={(event) => setPriority(event.target.value as TodoTaskRow['priority'])}><option value="low">Düşük</option><option value="normal">Normal</option><option value="high">Yüksek</option></select></label></div><label className={styles.todoAgendaToggle}><input type="checkbox" checked={inAgenda} onChange={(event) => setInAgenda(event.target.checked)} /> Ajandada göster</label>{inAgenda && <div className={styles.todoAgendaFields}><label>Tarih<input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label>Zaman dilimi<select value={slotId} onChange={(event) => setSlotId(event.target.value)}>{slots.map((slot) => <option key={slot.id} value={slot.id}>{slot.name}</option>)}</select></label><label>Bildirim<input type="time" value={reminder} onChange={(event) => setReminder(event.target.value)} /></label></div>}<div className={styles.noteActions}>{onDelete && <button type="button" className={styles.noteDelete} onClick={() => void onDelete()}>Sil</button>}<span /><button className={styles.primary} disabled={busy || !title.trim() || (inAgenda && (!date || !slotId))}>{busy ? 'Kaydediliyor…' : 'Kaydet'}</button></div></form></div>;
}
